### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by lorriborri** [bhprin/log4j-vul#1]
Could you please attach a license file, for example MIT, Apache 2.0, GPL. A license file would make clear what I am allowed to do with this code and what not.
About the background: I am a student at the University of Ulm and am currently writing my my master thesis.
For my empirical study I am investigating vulnerable projects and evaluating different security tools.
I would like to choose your project as one of my test cases for my empirical study.
However, since there is no license file available, I am not sure if I am allowed to use this code for my empirical study or not.
Thank you! :)

**Comment by bhprin** [comment]
Hi please feel free to use this code. I do not have any objections. 
RegardsBhanu Prakash 

Sent from Yahoo Mail on Android 
 
  On Wed, 14 Dec 2022 at 21:49, ***@***.***> wrote:   


Could you please attach a license file, for example MIT, Apache 2.0, GPL. A license file would make clear what I am allowed to do with this code and what not.
About the background: I am a student at the University of Ulm and am currently writing my my master thesis.
For my empirical study I am investigating vulnerable projects and evaluating different security tools.
I would like to choose your project as one of my test cases for my empirical study.
However, since there is no license file available, I am not sure if I am allowed to use this code for my empirical study or not.
Thank you! :)

**Comment by bhprin** [comment]
Added MT License
